Update docs and labels for CXR-3 release
lindawangg/COVID-Net pull request #227
Opened 2022-06-02 14:46 UTC by haydengunraj

# Pull Request Template

## Description

Add cleaned CXR-3 label files, update README and COVIDx docs.

## Context of change

Please add options that are relevant and mark any boxes that apply.

- [ ] Software (software that runs on the PC)
- [ ] Library (library that runs on the PC)
- [ ] Tool (tool that assists coding development)
- [X] Documentation and/or labels

## Type of change

Please mark any boxes that apply.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [X] Dataset release

## How Has This Been Tested?

N/A

## Checklist:

Please mark any boxes that have been completed.

- [X] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

2022-06-03 14:38 UTC, h-aboutalebi requested changes

2022-06-03 14:38 UTC, h-aboutalebi commented on README.md
> -1. COVIDNet-CXR models (COVID-19 detection using chest x-rays): https://github.com/lindawangg/COVID-Net/blob/master/docs/models.md
Please also add CovidNet-BioChem:
[COVID-Net Biochem](https://github.com/h-aboutalebi/CovidBiochem)

2022-06-03 14:38 UTC, h-aboutalebi commented on docs/train_eval_inference.md
> +    --trainfile labels/train_COVIDx_CXR-3A.txt \
Instead of using train_COVIDx_CXR-3A or train_COVIDx_CXR-3B in our releases, it might be a better idea to use train_COVIDx_CXR-3.1, train_COVIDx_CXR-3.2 so the customer have a better understanding of the new update.

2022-06-03 14:38 UTC, h-aboutalebi commented on eval.py
> -    parser.add_argument('--testfile', default='labels/test_COVIDx9B.txt', type=str, help='Name of testfile')
Same here. test_COVIDx9B does not give me any information on what version it is being used. It makes it also difficult to track previous versions.

2022-06-03 15:48 UTC, AlexSWong commented on README.md
> -1. COVIDNet-CXR models (COVID-19 detection using chest x-rays): https://github.com/lindawangg/COVID-Net/blob/master/docs/models.md
@h-aboutalebi This repo is for CXR only.  I have separate repo for the portal that points to biochem already.

2022-06-03 15:49 UTC, AlexSWong commented on docs/train_eval_inference.md
> +    --trainfile labels/train_COVIDx_CXR-3A.txt \
@h-aboutalebi A and B refers to the same update but with 3-class and 2-class annotations.  It's not different versions so 3.1 and 3.2 wouldn't be appropriate.

2022-06-03 16:12 UTC, AlexSWong commented on eval.py
> -    parser.add_argument('--testfile', default='labels/test_COVIDx9B.txt', type=str, help='Name of testfile')
let's just focus on the new release and not cleaning up the old ones.   For the new datasets COVIDx CXR 3A and 3B, do you think it would just be clearer if it was COVIDx CXR3-2class and CXR3-3class?

2022-06-03 16:15 UTC, h-aboutalebi approved these changes

2022-06-04 21:00 UTC, haydengunraj commented on eval.py
> -    parser.add_argument('--testfile', default='labels/test_COVIDx9B.txt', type=str, help='Name of testfile')
Yeah it might be clearer that way, we can use that scheme going forward.

2026-03-20 16:10 UTC, merged