COVIDx5 datasets
lindawangg/COVID-Net pull request #98
Opened 2020-10-27 16:31 UTC by NaomiTerhljan

# Pull Request Template

## Description

Adds the new COVIDx5 dataset train and test files. Numbers are consistent with the current numbers in create_COVIDx.ipynb.

## Type of change

Please mark any boxes that apply.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Checklist:

Please mark any boxes that have been completed.

- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

2020-10-28 01:05 UTC, mayaliliya commented on docs/COVIDx.md
>  Patients distribution
Hey Naomi, do you know if we can use the create_COVIDx.ipynb to get the newest patient distribution count?

2020-10-28 20:39 UTC, maclean-alexander requested changes
test_COVIDx5.txt should have the same test files listed as in previous (i.e. x4) versions.

2020-10-29 00:53 UTC, NaomiTerhljan commented on docs/COVIDx.md
>  Patients distribution
Hey @mayaliliya , there wasn't a way so I added a new cell to the create_COVIDx.ipynb which calculates it! 
![Screenshot from 2020-10-28 20-51-04](https://user-images.githubusercontent.com/62967180/97512278-7c202100-195f-11eb-8a1b-4f426bb63180.png) Do we want this extra cell added to the notebook in the repo for future use?

2020-10-29 01:45 UTC, maclean-alexander approved these changes

2020-10-30 15:11 UTC, mayaliliya approved these changes

2020-10-30 15:11 UTC, merged